{% set version = "0.3.0" %}

package:
  name: springcraft
  version: {{ version }}

source:
  url: https://github.com/biotite-dev/springcraft/archive/v{{ version }}.tar.gz
  sha256: e1b2fbe77ae77078f6170b9c8fec85c6552d6a9559891e048bbba3fc084da65b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - numpy >=1.15
    - biotite >=0.32

test:
  source_files:
    - tests/
  requires:
    - pytest
    - prody
    - python {{ python_min }}
  commands:
    - pytest --ignore tests/test_version.py

about:
  home: https://springcraft.biotite-python.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Investigate molecular dynamics with elastic network models
  doc_url: https://springcraft.biotite-python.org
  dev_url: https://github.com/biotite-dev/springcraft

extra:
  recipe-maintainers:
    - padix-key
